apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-api-proxy
  labels:
    app: ollama-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-api-proxy
  template:
    metadata:
      labels:
        app: ollama-api-proxy
    spec:
      containers:
      - name: ollama-api-proxy
        image: ${CONTAINER_REPOSITORY}/ollama-api-proxy:latest
        env:
        - name: OLLAMA_URL
          value: http://ollama-service:80
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"