apiVersion: v1
kind: Service
metadata:
  name: chat-app-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 777       # Changed from 80 to any unused port
    targetPort: 80  # (internal container port - should be kept as 80)
  selector:
    app: chat-app-frontend